services:
  postgres:
    image: postgres:16
    container_name: hotel-postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_user -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: hotel-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

#  backend:
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
#    image: yourdockerhubuser/hotel-backend:latest
#    container_name: hotel-backend
#    depends_on:
#      postgres:
#        condition: service_healthy
#      minio:
#        condition: service_started
#    env_file:
#      - ../backend/.env.prod
#    environment:
#      NODE_ENV: production
#    ports:
#      - "3000:3000"
#    command: sh -c "npx prisma migrate deploy && node dist/src/main"

volumes:
  postgres_data:
  minio_data:
